"""add ppg recordings and samples

Revision ID: 44ec2f09d933
Revises: cdf73bb6afec
Create Date: 2026-09-01 19:38:24.679685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ec2f09d933'
down_revision = 'cdf73bb6afec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppg_recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('sample_rate_hz', sa.Float(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ppg_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppg_recordings_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppg_recordings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppg_recordings_started_at'), ['started_at'], unique=False)

    op.create_table('ppg_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_offset_ms', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['ppg_recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ppg_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppg_samples_recording_id'), ['recording_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ppg_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppg_samples_recording_id'))

    op.drop_table('ppg_samples')
    with op.batch_alter_table('ppg_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppg_recordings_started_at'))
        batch_op.drop_index(batch_op.f('ix_ppg_recordings_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_ppg_recordings_patient_id'))

    op.drop_table('ppg_recordings')
    # ### end Alembic commands ###
