"""add ml models and inferences

Revision ID: 46015efa6a55
Revises: 44ec2f09d933
Create Date: 2026-09-01 19:47:41.588997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46015efa6a55'
down_revision = '44ec2f09d933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_inferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('inference_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['ppg_recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_inferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_inferences_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_inferences_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_inferences_recording_id'), ['recording_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_inferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_inferences_recording_id'))
        batch_op.drop_index(batch_op.f('ix_ml_inferences_model_id'))
        batch_op.drop_index(batch_op.f('ix_ml_inferences_executed_at'))

    op.drop_table('ml_inferences')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
