"""add edge gateways and devices

Revision ID: 583afb5200e8
Revises: ca187cc309e4
Create Date: 2026-09-01 18:49:57.788712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583afb5200e8'
down_revision = 'ca187cc309e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_gateways',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gateway_uid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edge_gateways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edge_gateways_gateway_uid'), ['gateway_uid'], unique=True)

    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_uid', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('hardware_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gateway_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['edge_gateways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_uid'), ['device_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_gateway_id'), ['gateway_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_gateway_id'))
        batch_op.drop_index(batch_op.f('ix_devices_device_uid'))

    op.drop_table('devices')
    with op.batch_alter_table('edge_gateways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edge_gateways_gateway_uid'))

    op.drop_table('edge_gateways')
    # ### end Alembic commands ###
