"""add sensors and measurement types

Revision ID: b521956e1357
Revises: 583afb5200e8
Create Date: 2026-09-01 19:14:09.016135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b521956e1357'
down_revision = '583afb5200e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurement_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_types_code'), ['code'], unique=True)

    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_uid', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensors_sensor_uid'), ['sensor_uid'], unique=True)

    op.create_table('sensor_measurement_types',
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('measurement_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_type_id'], ['measurement_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sensor_id', 'measurement_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_measurement_types')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_sensor_uid'))
        batch_op.drop_index(batch_op.f('ix_sensors_device_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('measurement_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_types_code'))

    op.drop_table('measurement_types')
    # ### end Alembic commands ###
