"""add observations and observation values

Revision ID: cdf73bb6afec
Revises: b521956e1357
Create Date: 2026-09-01 19:27:58.219163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf73bb6afec'
down_revision = 'b521956e1357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('measurement_type_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_type_id'], ['measurement_types.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_measurement_type_id'), ['measurement_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_sensor_id'), ['sensor_id'], unique=False)

    op.create_table('observation_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('integer_value', sa.Integer(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_values_observation_id'), ['observation_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_values_observation_id'))

    op.drop_table('observation_values')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_observations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_observations_measurement_type_id'))

    op.drop_table('observations')
    # ### end Alembic commands ###
